### ISSUE TITLE
2021.7.20 Update Failure

### ISSUE THREAD

**Issue by RJ-Make** [marius-wieschollek/passwords#393]
### System Information

 Nextcloud Version: 21.0.3
 PHP Version: 7.4.3
 Server OS and Version: ostgreSQL 12.7 (Ubuntu 12.7-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit

Passwords Version: 2021.6.20

### Steps to reproduce
Install 2021.7.20 update via NC Web App Interface

### Expected result
Install Succeed. 

### Actual result
Failure. From there I'm locked out. Tried updating via the VM command line update, but I don't think that is the proper way. 

<img width="353" alt="2021-07-03_6-40-23" src="https://user-images.githubusercontent.com/8496835/124351938-540e4f00-dbcb-11eb-88cc-4c33a35aab98.png">

<img width="543" alt="2021-07-03_6-40-43" src="https://user-images.githubusercontent.com/8496835/124351942-58d30300-dbcb-11eb-84ef-42ab80caa016.png">

**Comment by orlovnv** [comment]
have the same problem, An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "pw_password_index" already exists

**Comment by marius-wieschollek** [comment]
I just published the [nightly 2021.7.21-build4188](https://apps.nextcloud.com/apps/passwords/releases?platform=21#21) to the appstore. Can you confirm that it fixes the issue?

**Comment by NemoNumquam** [comment]
I have just tried to install passwords and get this error "An exception occurred while executing 'SELECT `a`.* FROM `oc_passwords_entity_challenge` `a`': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextCloudDB.oc_passwords_entity_challenge' doesn't exist " It would appear that the tables created do not have "entity" in the name. I am using mysql v8

**Comment by marius-wieschollek** [comment]
I published a nightly which should also fix that.

**Comment by staeglis** [comment]
The issue still persists:
```
$ sudo -u www-data /var/www/html/occ app:enable passwords -n
An exception occurred while executing 'CREATE UNIQUE INDEX pw_password_index ON oc_passwords_password (user_id, uuid)':

SQLSTATE[42P07]: Duplicate table: 7 FEHLER:  Relation »pw_password_index« existiert bereits
```

**Comment by marius-wieschollek** [comment]
@staeglis Which build did you try?

**Comment by staeglis** [comment]
@marius-wieschollek Sorry I haven't seen the right link. With this build it's working:
https://git.mdns.eu/nextcloud/passwords/-/jobs/12554/artifacts/raw/passwords.tar.gz

**Comment by marius-wieschollek** [comment]
Ok. I merged it and the update should be available in the appstore in a few minutes.

**Comment by r3pek** [comment]
@marius-wieschollek I don't thing this is fixed yet. I was just running the update and hit the same problem. I've downloaded the version available on the apps.nextcloud.com website (job 12568) and it still doesn't upgrade correctly. I get 4 of this errors on the upgrade:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'`

All of them trying to re'INSERT an entry into the `passwords_folder` table.

**Comment by marius-wieschollek** [comment]
@r3pek This does not seem to be the same error. Please make a separate bug report for this issue.

**Comment by gcclinux** [comment]
Hello,

I am still seeing the same error, has there been any more updates that I missed?

```
$ sudo -u www-data php occ app:enable passwords
An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "pw_password_index" already exists
```
Many Thanks

**Comment by gcclinux** [comment]
Hello,  i can confirm it worked and passwords is once more fully functioning but I had to restore the password from a backup as they had all gone. 

At least I the app works again and the restore also. 

Thank you
