### ISSUE TITLE
Web app for passwords doesn't load at all

### ISSUE THREAD

**Issue by rubikonx9** [marius-wieschollek/passwords#522]
### System Information
**Server:**
```json
{
    "version": {
        "server": "24.0.3.2",
        "app": "2022.6.20",
        "lsr": false,
        "php": "8.1.8",
        "cronPhp": "8.1.8"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "pageres",
        "security": "hibp",
        "words": "random",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "status": {
        "autoBackupRestored": false
    },
    "apps": {
        "guests": {
            "installed": false,
            "enabled": false
        },
        "occweb": {
            "installed": false,
            "enabled": false
        },
        "theming": {
            "installed": true,
            "enabled": true
        },
        "passman": {
            "installed": false,
            "enabled": false
        },
        "unsplash": {
            "installed": false,
            "enabled": false
        },
        "impersonate": {
            "installed": true,
            "enabled": true
        },
        "passwords_handbook": {
            "installed": false,
            "enabled": false
        }
    },
    "sharing": {
        "shares": 0
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
Firefox 103 on Windows 10
Chromium 105 on Windows 10
Brave 1.41 on Arch Linux
Brave 1.40 for Android 
```
Basically any client I tried.

### Steps to reproduce
1. Open Nextcloud page via web browser
2. Navigate to Passwords app

### Expected result
Passwords app should be displayed normally.

### Actual result
Preloader for passwords app is displayed (rotating circle). Nothing happens beyond that. It never stops and nothing more is ever shown.

### Additional info
This app used to work in the past - I suspect it started happenning at last app update (but can't confirm 100%, as there's no way to downgrade apps).

Other APIs concerning the Passwords app work just fine - namely, I use Firefox extension and Android Passwords app, and they work with no problems.
So it seems the problem only concerns the web app.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
I set Nextcloud log level to 0 (DEBUG) in `config.php`.

Here's the `tail -f /var/log/nextcloud/nextcloud.log | grep pass` when I try to open the app.

There's an exception about `FILTER_SANITIZE_STRING`.

I can't use Settings -> Logging via web interface, as it throws React errors :)

```
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"drawio","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"drawio"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"extract","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"extract"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"files_texteditor","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"files_texteditor"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"maps","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"maps"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"metadata","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"metadata"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"video_converter","method":"GET","url":"/apps/passwords/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"video_converter"}}
{"reqId":"some-req-id","level":3,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"PHP","method":"GET","url":"/apps/passwords/","message":"Constant FILTER_SANITIZE_STRING is deprecated at /var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php#621","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","exception":{"Exception":"Error","Message":"Constant FILTER_SANITIZE_STRING is deprecated at /var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php#621","Code":0,"Trace":[{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":621,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":557,"function":"getClientFromRequest","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":504,"function":"getUserInfoFromPassword","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":375,"function":"loadUserFromSession","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":359,"function":"loadUserInformation","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"file":"/var/lib/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":185,"function":"determineAppMode","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"function":"__construct","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":89,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"array_map"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":89,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"array_map"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":89,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"array_map"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":89,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":108,"function":"array_map"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":133,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":465,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":437,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":159,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"scss_cacher","method":"GET","url":"/apps/passwords/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"scss_cacher"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"scss_cacher","method":"GET","url":"/apps/passwords/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"scss_cacher"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"scss_cacher","method":"GET","url":"/apps/passwords/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"scss_cacher"}}
{"reqId":"some-req-id","level":0,"time":"2022-07-27T07:52:35+00:00","remoteAddr":"111.111.111.111","user":"username","app":"scss_cacher","method":"GET","url":"/apps/passwords/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:103.0) Gecko/20100101 Firefox/103.0","version":"24.0.3.2","data":{"app":"scss_cacher"}}
```
</details>

### Browser log
<details>
<summary>Browser log</summary>
Only some debug and warning messages.
They seem unrelated.

```
No OC found
getLanguage @ index.js:46
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.0
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
2globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
App.vue:150 Loading theming data for notification bell styling
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
App.vue:160 Registering notifications container as a menu
2globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
App.vue:412 Notifications permissions not yet requested
App.vue:355 Polling interval updated to 30000
App.vue:217 Started background fetcher as session_keepalive is enabled
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
session-heartbeat.js:103 session heartbeat polling started
/apps/passwords/#/:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden" method=​"POST">​…​</form>​
ConsoleLogger.js:29 [DEBUG] unified-search: Unified Search initialized with the following providers Object
5globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
App.vue:318 Got notification data
App.vue:355 Polling interval updated to 30000
59globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
Tt @ globals.js:62
```
</details>

**Comment by omocinteractive** [comment]
... same here. The chrome app sometimes doesn't load all password, sometimes the false passwords, sometimes nothing and sometimes .htaccess basic logins are blocked (after disabling the app, everything okay). No error messages. The web app work correct.

**Comment by omocinteractive** [comment]
My log is full of this:

  "error": {
    "name": "Error",
    "stack": "Error: No tab with id: 2048311311.\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:2:739937",
    "string": "Error: No tab with id: 2048311311.",
    "message": "No tab with id: 2048311311."
  }

**Comment by marius-wieschollek** [comment]
This is an seems to be caused by a constant being used by the app which is deprecated in PHP 8.1. You can try the nightly builds where the issue should be resolved.

**Comment by rubikonx9** [comment]
I have upgraded to `2022.8.20-build4529`.
I also made a minor upgrade of Nextcloud in the meantime. Currently, my system status is:
```

{
    "version": {
        "server": "24.0.4.1",
        "app": "2022.8.20-build4529",
        "lsr": false,
        "php": "8.1.9",
        "cronPhp": "8.1.9"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "pageres",
        "security": "hibp",
        "words": "random",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": true,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

Now, the debug-level logs for a single request are:
```
{"reqId":"some-req","level":1,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Passwords runs /usr/share/webapps/nextcloud/cron.php in global mode","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Deleted 0 orphaned password(s)","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Deleted 0 expired share(s)","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Created 0 new share(s)","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Removed shared attribute from 0 password(s)","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Updated 0 share(s)","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Closed and deleted 0 sessions permanently","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Deleted 0 registrations permanently","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
{"reqId":"some-req","level":0,"time":"2022-08-22T05:20:03+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"Deleted 0 object(s) permanently","userAgent":"--","version":"24.0.4.1","data":{"app":"passwords"}}
```

No more errors!
Sadly, the page still doesn't load at all :( Nothing changed in the browser.

**Comment by rubikonx9** [comment]
The problem was on the side of my Nextcloud setup.
Basically, I had two versions of the app running in parallel, and while `occ` and GUI Admin panel reported the latest one, in fact the older one was loaded when navigating via the browser.

I raised an issue about it in the Nextcloud repo: https://github.com/nextcloud/server/issues/33794

The fact that having two versions of an app causes unexpected side-effect is actually known there, but I think it deserves some improvement.

Anyway, it turns out that the problem wasn't related to Passwords app at all - it was just another problem that accidentally made itself apparent here.
